// Retrive Movie
export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS'
export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS'
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SIMILAR_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SIMILAR_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_REVIEW_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_REVIEW_SUCCESS'

// Retrieve TV
export const RETRIEVE_TV_DETAILS_SIMILAR_SUCCESS = 'RETRIEVE_TV_DETAILS_SIMILAR_SUCCESS';
export const RETRIEVE_TV_SEARCH_RESULT_SUCCESS = 'RETRIEVE_TV_SEARCH_RESULT_SUCCESS';
// Retrieve PERSON
export const RETRIEVE_PERSON_SEARCH_RESULT_SUCCESS = 'RETRIEVE_PERSON_SEARCH_RESULT_SUCCESS';